---
kind: Service
apiVersion: v1
metadata:
  name: test-summon-init-app-backend
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: test-summon-init-app-backend
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: summon-init-mysql
  labels:
    app: test-summon-init-app-backend
spec:
  serviceName: test-summon-init-app-backend
  selector:
    matchLabels:
      app: test-summon-init-app-backend
  template:
    metadata:
      labels:
        app: test-summon-init-app-backend
    spec:
      containers:
      - name: test-summon-init-app-backend
        # Use 8.0 over 5.7 to resolve TLS version mismatch in OpenShift/RHEL.
        image: {{ TEST_SUMMON_MYSQL_IMAGE }}
        imagePullPolicy: Always
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_USER
            value: test_app
          - name: MYSQL_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: MYSQL_DATABASE
            value: test_app

---
kind: Service
apiVersion: v1
metadata:
  name: test-summon-sidecar-app-backend
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: test-summon-sidecar-app-backend
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: summon-sidecar-mysql
  labels:
    app: test-summon-sidecar-app-backend
spec:
  serviceName: test-summon-sidecar-app-backend
  selector:
    matchLabels:
      app: test-summon-sidecar-app-backend
  template:
    metadata:
      labels:
        app: test-summon-sidecar-app-backend
    spec:
      containers:
      - name: test-summon-sidecar-app-backend
        # Use 8.0 over 5.7 to resolve TLS version mismatch in OpenShift/RHEL.
        image: {{ TEST_SUMMON_MYSQL_IMAGE }}
        imagePullPolicy: Always
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_USER
            value: test_app
          - name: MYSQL_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: MYSQL_DATABASE
            value: test_app

---
kind: Service
apiVersion: v1
metadata:
  name: test-secretless-app-backend
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: test-secretless-app-backend
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secretless-mysql
  labels:
    app: test-secretless-app-backend
spec:
  serviceName: test-secretless-app-backend
  selector:
    matchLabels:
      app: test-secretless-app-backend
  template:
    metadata:
      labels:
        app: test-secretless-app-backend
    spec:
      containers:
      - name: test-secretless-app-backend
        # Use over 5.7 over 8.0 as this does not have the TLS version mismatch
        # issue in OpenShift/RHEL. This does have an issue with
        # centos/mysql-80-centos8 due to lack of support for new auth mechanisms
        # from 8.0
        image: {{ TEST_SECRETLESS_MYSQL_IMAGE }}
        imagePullPolicy: Always
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_USER
            value: test_app
          - name: MYSQL_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: MYSQL_DATABASE
            value: test_app
